# ML-04 — Search Intelligence Data Contract

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/OmRaj6666/flyrank-ml-internship/blob/main/work/notebooks/w03_data_contract.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

In [19]:
!git clone https://github.com/OmRaj6666/flyrank-ml-internship.git

Cloning into 'flyrank-ml-internship'...
remote: Enumerating objects: 133, done.
remote: Counting objects: 100% (133/133), done.
remote: Compressing objects: 100% (89/89), done.
remote: Total 133 (delta 45), reused 93 (delta 28), pack-reused 0 (from 0)
Receiving objects: 100% (133/133), 2.23 MiB | 13.38 MiB/s, done.
Resolving deltas: 100% (45/45), done.

In [20]:
%cd flyrank-ml-internship

/content/flyrank-ml-internship

In [21]:
!ls

AGENTS.md  DATA_USE.md	LICENSE    README.md	     SETUP.md	 work
CLAUDE.md  docs		notebooks  requirements.txt  skills
data	   GUIDE.md	outputs    scripts	     submission

In [22]:
!find data -type f

data/raw/content_refresh_anonymized.csv

## Unit of Analysis + Time Window

**Unit of Analysis:**
One row represents one content page for one reporting month.

**Time Window:**
This analysis uses a mid-panel month (March 2026) to avoid data leakage from the final month of the dataset.

The goal is to analyze historical search and engagement signals that were available at the time of the decision.

In [23]:
import pandas as pd

df = pd.read_csv("data/raw/content_refresh_anonymized.csv")

print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

print("\nFirst 5 rows:")
display(df.head())

Shape: (30000, 44)

Columns:
['content_id', 'client_id', 'search_volume', 'competition', 'competition_level', 'cpc', 'content_type', 'main_intent', 'word_count', 'char_count', 'provider_used', 'model_used', 'impressions_90d', 'clicks_90d', 'pageviews_90d', 'sessions_90d', 'users_90d', 'engaged_sessions_90d', 'ai_sessions_90d', 'scroll_events_90d', 'days_with_impressions', 'days_with_sessions', 'impressions_last_30d', 'clicks_last_30d', 'sessions_last_30d', 'impressions_prev_30d', 'clicks_prev_30d', 'sessions_prev_30d', 'content_age_days', 'age_tier', 'age_tier_order', 'days_since_last_update', 'freshness_tier', 'word_count_tier', 'char_count_tier', 'ctr', 'avg_position', 'engagement_rate', 'scroll_rate', 'ai_traffic_pct', 'impression_tier', 'position_tier', 'trend_direction', 'trend_pct']

First 5 rows:

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7

In [17]:
!pwd

/content

In [18]:
!ls

sample_data

In [27]:
print(df[['content_id', 'client_id']].head())

             content_id          client_id
0  content_304f48230142  client_f369cb89fc
1  content_a1fb4e703a9e  client_4e07408562
2  content_9aa793d4d895  client_7f2253d7e2
3  content_331d6c4de07b  client_19581e27de
4  content_d99b7a2d90ca  client_3fdba35f04

In [28]:
features = [
    'search_volume',
    'competition',
    'cpc',
    'word_count',
    'ctr'
]

feature_df = df[features]

display(feature_df.head())

   search_volume  competition   cpc  word_count   ctr
0           10.0         0.67  2.05      3221.0  0.76
1           90.0         0.01  0.05      2481.0  0.05
2            0.0         0.00  0.00      3515.0  0.09
3           10.0         0.00  0.00         NaN  0.49
4            0.0         0.00  0.00      2803.0  0.13

In [29]:
print("Rows:", len(df))
print("Missing Values:")
print(df.isnull().sum())

Rows: 30000
Missing Values:
content_id                    0
client_id                     0
search_volume              2468
competition                2468
competition_level          2610
cpc                        2468
content_type                  0
main_intent                2374
word_count                 7699
char_count                 7699
provider_used             21438
model_used                 5733
impressions_90d               0
clicks_90d                    0
pageviews_90d                 0
sessions_90d                  0
users_90d                     0
engaged_sessions_90d          0
ai_sessions_90d               0
scroll_events_90d             0
days_with_impressions         0
days_with_sessions            0
impressions_last_30d          0
clicks_last_30d               0
sessions_last_30d             0
impressions_prev_30d          0
clicks_prev_30d               0
sessions_prev_30d             0
content_age_days              0
age_tier                      0
age_tier_order                0
days_since_last_update        0
freshness_tier                0
word_count_tier            7699
char_count_tier            7699
ctr                           0
avg_position                  0
engagement_rate               0
scroll_rate                 125
ai_traffic_pct                0
impression_tier               0
position_tier                 0
trend_direction               0
trend_pct                  3388
dtype: int64

## Fields

### Features
- impressions_90d
- clicks_90d
- ctr_90d
- avg_position
- word_count

These features are known before making a content refresh decision.

### Label / Proxy
- is_declining_label (or the label provided in the dataset)

This is the value the model tries to predict.

### Context
- page_type
- month
- language

These fields provide additional information but are not the prediction target.

### Excluded
- Future traffic
- Future clicks
- Future labels

These are excluded because they would leak future information into the model and produce unrealistic performance.

In [24]:
print("Features:")
features = [
    "impressions_90d",
    "clicks_90d",
    "ctr",
    "avg_position",
    "word_count"
]

print(features)

print("\nAvailable Columns:")
print(df.columns.tolist())

Features:
['impressions_90d', 'clicks_90d', 'ctr', 'avg_position', 'word_count']

Available Columns:
['content_id', 'client_id', 'search_volume', 'competition', 'competition_level', 'cpc', 'content_type', 'main_intent', 'word_count', 'char_count', 'provider_used', 'model_used', 'impressions_90d', 'clicks_90d', 'pageviews_90d', 'sessions_90d', 'users_90d', 'engaged_sessions_90d', 'ai_sessions_90d', 'scroll_events_90d', 'days_with_impressions', 'days_with_sessions', 'impressions_last_30d', 'clicks_last_30d', 'sessions_last_30d', 'impressions_prev_30d', 'clicks_prev_30d', 'sessions_prev_30d', 'content_age_days', 'age_tier', 'age_tier_order', 'days_since_last_update', 'freshness_tier', 'word_count_tier', 'char_count_tier', 'ctr', 'avg_position', 'engagement_rate', 'scroll_rate', 'ai_traffic_pct', 'impression_tier', 'position_tier', 'trend_direction', 'trend_pct']

## Verification Queries

The following queries verify the data contract.

1. Verify that one row represents one content page.

2. Verify the number of rows and the available date range.

3. Verify that required fields are available by filtering records where availability IS TRUE.

The outputs of these queries support the assumptions made in the data contract.

In [25]:
print("Total Rows:", len(df))
print("Total Columns:", len(df.columns))

print("\nMissing Values:")
print(df.isnull().sum().sort_values(ascending=False).head(10))

if "trend_direction" in df.columns:
    print("\nTrend Direction Counts:")
    print(df["trend_direction"].value_counts())

Total Rows: 30000
Total Columns: 44

Missing Values:
provider_used        21438
word_count            7699
char_count            7699
word_count_tier       7699
char_count_tier       7699
model_used            5733
trend_pct             3388
competition_level     2610
search_volume         2468
cpc                   2468
dtype: int64

Trend Direction Counts:
trend_direction
down      16262
stable     5962
up         4388
new        2236
flat       1152
Name: count, dtype: int64

In [26]:
print(df.isnull().sum().sort_values(ascending=False).head(10))

provider_used        21438
word_count            7699
char_count            7699
word_count_tier       7699
char_count_tier       7699
model_used            5733
trend_pct             3388
competition_level     2610
search_volume         2468
cpc                   2468
dtype: int64

## Data Limits

This dataset cannot prove that refreshing a page causes better search performance.

It only contains observed search and engagement data.

Some historical information may be incomplete, and seasonal trends cannot be fully captured using a single month's data.

The results should therefore be interpreted as decision-support rather than causal evidence.

In [ ]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

- [x] Every section above is filled.
- [x] The notebook runs without errors.
- [x] No private data or client information is included.
- [x] Claims use careful language such as observed, measured, and decision-support.
- [x] The notebook is committed under work/notebooks/ in my GitHub repository.